### PR TITLE
ran npm install mocha --save-dev to make npm install mocha automatically

### PR DESCRIPTION
**Pull request by mikeblum**
Running ```npm install``` followed by ```npm test``` failed. Added mocha to the dev dependencies.

### CODE REVIEW

**Comment by boutell** [comment]
Hmm, wait, did you test this without mocha globally installed? The script
command in package.json is set up to run mocha without a path.

On Wed, Jun 15, 2016 at 1:22 PM, Michael Blum <notifications@github.com>
wrote:

> Running npm install followed by npm test failed. Added mocha to the dev
> dependencies.
> ------------------------------
> You can view, comment on, or merge this pull request online at:
>
>   https://github.com/punkave/sanitize-html/pull/111
> Commit Summary
>
>    - ran npm install mocha --save-dev to make npm install mocha
>    automatically
>
> File Changes
>
>    - *M* package.json
>    <https://github.com/punkave/sanitize-html/pull/111/files#diff-0> (3)
>
> Patch Links:
>
>    - https://github.com/punkave/sanitize-html/pull/111.patch
>    - https://github.com/punkave/sanitize-html/pull/111.diff
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/sanitize-html/pull/111>, or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fTZskqmyfThagf23uuFpDECKahusks5qMDTsgaJpZM4I2mKW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by mikeblum** [comment]
I don't have mocha installed globally. This way we can run `sanitize-html` and peg the version of mocha depending on our ```package.json``` rather than depending on user's global mocha version.

**Comment by boutell** [comment]
Just having trouble seeing how typing "npm test" works with this.

On Wed, Jun 15, 2016 at 1:27 PM, Michael Blum <notifications@github.com>
wrote:

> I don't have mocha installed globally. This way we can run sanitize-html
> and peg the version of mocha depending on our package.json rather than
> depending on user's global mocha version.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/sanitize-html/pull/111#issuecomment-226259249>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fQRbFTmCTKrU2Gd3NiQpGVXQGoRmks5qMDXzgaJpZM4I2mKW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by mikeblum** [comment]
both `npm test` and `npm run test` appear to execute the unit tests and I don't have mocha on my PATH.

**Comment by boutell** [comment]
I am stumped as to how they do that (: But, great!

On Wed, Jun 15, 2016 at 4:28 PM, Michael Blum <notifications@github.com>
wrote:

> both npm test and npm run test appear to execute the unit tests and I
> don't have mocha on my PATH.
>
> —
> You are receiving this because you modified the open/close state.
> Reply to this email directly, view it on GitHub
> <https://github.com/punkave/sanitize-html/pull/111#issuecomment-226309877>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AAB9fRFx6DnkqaaJjJOLj7XLEMeZHRHcks5qMGBggaJpZM4I2mKW>
> .
>



-- 


*THOMAS BOUTELL, *SUPPORT LEAD
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Pull request merged**
