### PR TITLE
On non-text tags, content should not be html-escaped.

### PR DESCRIPTION
**Pull request by aletorrado**

### CODE REVIEW

**Comment by aletorrado** [comment]
Please note that anytime a script tag is not allowed (this is the default), the content will not be in the output. But in case you allowed that tag, sanitize-html should not touch it's content.

**Comment by boutell** [comment]
How about an example of what it is doing wrong now?

**Comment by aletorrado** [comment]
Just imagine anything you can do with the characters of the escapeHtml function, into the style or script tags. Eg:

	<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1";
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

sanitize-html outputs (notice that it replaced the " character at line 5):

	<script>(function(d, s, id) {
		var js, fjs = d.getElementsByTagName(s)[0];
		if (d.getElementById(id)) return;
		js = d.createElement(s); js.id = id;
		js.src = &quot;//connect.facebook.net/es_ES/all.js#xfbml=1&quot;;
		fjs.parentNode.insertBefore(js, fjs);
	}(document, 'script', 'facebook-jssdk'));</script>

**Comment by boutell** [comment]
I see your point, and we know at this point that htmlparser2 was able to
figure out how to treat the characters; we should do what it does.

I'm good with this if you add unit tests to the pull request.


On Thu, Feb 5, 2015 at 10:12 AM, aletorrado <notifications@github.com>
wrote:

> Just imagine anything you can do with the characters of the escapeHtml
> function, into the style or script tags. Eg:
>
> <script>(function(d, s, id) {
>     var js, fjs = d.getElementsByTagName(s)[0];
>     if (d.getElementById(id)) return;
>     js = d.createElement(s); js.id = id;
>     js.src = "//connect.facebook.net/es_ES/all.js#xfbml=1";
>     fjs.parentNode.insertBefore(js, fjs);
> }(document, 'script', 'facebook-jssdk'));</script>
>
> sanitize-html outputs (notice that it replaced the " character at line 5):
>
> <script>(function(d, s, id) {
>     var js, fjs = d.getElementsByTagName(s)[0];
>     if (d.getElementById(id)) return;
>     js = d.createElement(s); js.id = id;
>     js.src = &quot;//connect.facebook.net/es_ES/all.js#xfbml=1&quot;;
>     fjs.parentNode.insertBefore(js, fjs);
> }(document, 'script', 'facebook-jssdk'));</script>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/pull/40#issuecomment-73061836>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by aletorrado** [comment]
Done!

**Comment by boutell** [comment]
Thanks!

**Comment by boutell** [comment]
(Published to npm.)

**Comment by aletorrado** [comment]
Great. Thanks!

**Pull request merged**
