### PR TITLE
Allow custom processing for text nodes

### PR DESCRIPTION
**Pull request by csabapalfi**
Please note that custom processing is done once text is already HTML escaped.

### CODE REVIEW

**Comment by csabapalfi** [comment]
This essentially fixes #28.

**Comment by boutell** [comment]
Nice - how about renaming it textFilter for consistency with the rest of
the API and adding a section to the README?

On Thu, Feb 12, 2015 at 5:08 PM, Csaba Palfi <notifications@github.com>
wrote:

> This essentially fixes #28
> <https://github.com/punkave/sanitize-html/issues/28>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/punkave/sanitize-html/pull/43#issuecomment-74163725>.
>



-- 


*THOMAS BOUTELL, *DEV & OPS
P'UNK AVENUE | (215) 755-1330  |  punkave.com

**Comment by csabapalfi** [comment]
Done.

**Comment by boutell** [comment]
Published as 1.6.0.

I made a tiny change: if textFilter is not set at all, we just escape the text. This is necessary for backwards compatibility for those who have set their own options without using our defaultOptions as a starting point. The behavior in that case should not change.

**Comment by boutell** [comment]
Thanks for the feature!

**Comment by csabapalfi** [comment]
Amazing! Thanks for merging!

**Pull request merged**
